steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/devcode-457115/sync-database:develop-$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/devcode-457115/sync-database:develop-$SHORT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'sync-pg-service',
      '--image', 'gcr.io/devcode-457115/sync-database:develop-$SHORT_SHA',
      '--region', 'us-east4',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--update-secrets', '/secrets/credential_notion.json=credential_notion:latest',
      '--update-secrets', '/secrets/credential_cafeleather.json=credential_cafeleather:latest'
      ]

images:
  - gcr.io/devcode-457115/sync-database:develop-$SHORT_SHA

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET